collections:
  elections:
    output: true
    permalink: /elections/:year/:month/:day/:title.html
  posts:
    output: true
permalink: /news/:year/:month/:day/:title.html

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "page"
      disable_subscribe_button: false
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "elections"
    values:
      layout: "election"
  -
    scope:
      path: "manifesto"
      type: "pages"
    values:
      layout: "policy"
      editable: true
  -
    scope:
      path: "manifesto/constituencies"
      type: "pages"
    values:
      layout: "local_policy"
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
  - jekyll-feed
feed:
  path: news.rss
github:
  organisation: somethingnewuk
  pages_domain: somethingnewuk.github.io
  finances_repo: finances