defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      disable_subscribe_button: false
  -
    scope:
      path: "_posts/news"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "_posts/elections"
      type: "posts"
    values:
      layout: "election"
  -
    scope:
      path: "manifesto"
      type: "pages"
    values:
      layout: "policy"
      editable: true
  -
    scope:
      path: "manifesto/constituencies"
      type: "pages"
    values:
      layout: "local_policy"
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
  - jekyll-feed
feed:
  path: news.rss
permalink: /:categories/:year/:month/:day/:title.html
github:
  organisation: somethingnewuk
  pages_domain: somethingnewuk.github.io
  finances_repo: finances