defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "news"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "elections"
      type: "posts"
    values:
      layout: "election"
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
  - jekyll-feed
feed:
  path: news.rss
permalink: /:categories/:year/:month/:day/:title.html
github:
  organisation: somethingnewuk
  pages_domain: somethingnewuk.github.io
  finances_repo: finances