defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "news"
      type: "posts"
    values:
      layout: "post"
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
  - jekyll-feed
feed:
  path: news.rss
permalink: /:categories/:year/:month/:day/:title.html